# Generated by Django 4.2.3 on 2023-07-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[(1, 'Fêmea'), (2, 'Macho')], max_length=10)),
                ('imagem_principal_path', models.CharField(max_length=200)),
                ('num_imagens_extra', models.IntegerField(default=0)),
                ('descricao_do_animal', models.TextField()),
                ('esterilizado', models.CharField(choices=[(1, 'Esterilizado'), (2, 'Não Esterilizado'), (3, 'Desconhecido')], max_length=10)),
                ('vacinado', models.CharField(choices=[(1, 'Vacinas em Dia'), (2, 'Algumas Vacinas'), (3, 'Não Vacinado'), (4, 'Desconhecido')], max_length=10)),
                ('desparasitado', models.CharField(choices=[(1, 'Desparasitado'), (2, 'Não Desparasitado'), (3, 'Desconhecido')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anunciante', models.CharField(max_length=50)),
                ('localidade_anunciante', models.CharField(max_length=20)),
                ('contacto_telefonico_anunciante', models.CharField(max_length=9)),
                ('email_anunciante', models.CharField(max_length=100)),
                ('datetime_anuncio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicoesParaAnunciar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CorDoPelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte_tamanho', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300)),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Idade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PorteTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte_tamanho', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SobreProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('agradecimentos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasDoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_do_pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50)),
                ('tipo_de_animal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.tipodeanimal')),
            ],
        ),
        migrations.CreateModel(
            name='ImagensExtraAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_path', models.CharField(max_length=200)),
                ('id_animal_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AssociacoesDeAnimais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localidade', models.CharField(max_length=30)),
                ('website_ou_rede_social', models.CharField(max_length=200)),
                ('id_zona_do_pais_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.zonasdopais')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='id_anuncio_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.anuncio'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_cor_do_pelo_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.cordopelo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_idade_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.idade'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_porte_tamanho_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.portetamanho'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_raca_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.raca'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_tipo_de_animal_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.tipodeanimal'),
        ),
    ]
