# Generated by Django 4.2.3 on 2023-07-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0002_rename_porte_tamanho_cordopelo_cor_do_pelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animal'},
        ),
        migrations.AlterModelOptions(
            name='anuncio',
            options={'verbose_name_plural': 'Anúncio'},
        ),
        migrations.AlterModelOptions(
            name='associacoesdeanimais',
            options={'verbose_name_plural': 'Associações de Animais'},
        ),
        migrations.AlterModelOptions(
            name='condicoesparaanunciar',
            options={'verbose_name_plural': 'Condições para anunciar'},
        ),
        migrations.AlterModelOptions(
            name='cordopelo',
            options={'verbose_name_plural': 'Cor do Pêlo'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Faq'},
        ),
        migrations.AlterModelOptions(
            name='idade',
            options={'verbose_name_plural': 'Idade'},
        ),
        migrations.AlterModelOptions(
            name='imagensextraanimal',
            options={'verbose_name_plural': 'Imagens Extra Animal'},
        ),
        migrations.AlterModelOptions(
            name='portetamanho',
            options={'verbose_name_plural': 'Porte / Tamanho'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name_plural': 'Raça'},
        ),
        migrations.AlterModelOptions(
            name='sobreprojeto',
            options={'verbose_name_plural': 'Sobre o Projeto'},
        ),
        migrations.AlterModelOptions(
            name='tipodeanimal',
            options={'verbose_name_plural': 'Tipo De Animal'},
        ),
        migrations.AlterModelOptions(
            name='zonasdopais',
            options={'verbose_name_plural': 'Zona Do País'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='desparasitado',
            field=models.CharField(choices=[('1', 'Desparasitado'), ('2', 'Não Desparasitado'), ('3', 'Desconhecido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='esterilizado',
            field=models.CharField(choices=[('1', 'Esterilizado'), ('2', 'Não Esterilizado'), ('3', 'Desconhecido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('1', 'Fêmea'), ('2', 'Macho')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacinado',
            field=models.CharField(choices=[('1', 'Vacinas em Dia'), ('2', 'Algumas Vacinas'), ('3', 'Não Vacinado'), ('4', 'Desconhecido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='associacoesdeanimais',
            name='id_zona_do_pais_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.zonasdopais', verbose_name='Zona do País'),
        ),
        migrations.AlterField(
            model_name='zonasdopais',
            name='zona_do_pais',
            field=models.CharField(max_length=20, verbose_name='Zona do País'),
        ),
    ]
