# Generated by Django 4.2.3 on 2023-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0003_alter_animal_options_alter_anuncio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='imagem_principal_path',
        ),
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(default='animal-placeholder.jpg', upload_to='imagens'),
        ),
        migrations.DeleteModel(
            name='ImagensExtraAnimal',
        ),
    ]
