# Generated by Django 4.2.3 on 2023-07-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0004_remove_animal_imagem_principal_path_animal_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='num_imagens_extra',
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
