# Generated by Django 4.2.3 on 2023-07-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0005_remove_animal_num_imagens_extra_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='imagens/animais/'),
        ),
    ]
