# Generated by Django 4.2.3 on 2023-07-21 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0006_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_anuncio_FK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.anuncio'),
        ),
    ]
