# Generated by Django 4.2.3 on 2023-07-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0007_alter_animal_id_anuncio_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('1', 'Fêmea'), ('2', 'Macho')], max_length=10)),
                ('imagem', models.ImageField(upload_to='imagens/animais/')),
                ('descricao_do_animal', models.TextField()),
                ('esterilizado', models.CharField(choices=[('1', 'Esterilizado'), ('2', 'Não Esterilizado'), ('3', 'Desconhecido')], max_length=10)),
                ('vacinado', models.CharField(choices=[('1', 'Vacinas em Dia'), ('2', 'Algumas Vacinas'), ('3', 'Não Vacinado'), ('4', 'Desconhecido')], max_length=10)),
                ('desparasitado', models.CharField(choices=[('1', 'Desparasitado'), ('2', 'Não Desparasitado'), ('3', 'Desconhecido')], max_length=10)),
                ('nome_anunciante', models.CharField(max_length=50)),
                ('localidade_anunciante', models.CharField(max_length=20)),
                ('contacto_telefonico_anunciante', models.CharField(max_length=9)),
                ('email_anunciante', models.CharField(max_length=100)),
                ('datetime_anuncio', models.DateTimeField(auto_now_add=True)),
                ('id_cor_do_pelo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.cordopelo')),
                ('id_idade_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.idade')),
                ('id_porte_tamanho_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.portetamanho')),
                ('id_raca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.raca')),
                ('id_tipo_de_animal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.tipodeanimal')),
            ],
            options={
                'verbose_name_plural': 'Anúncio do Animal',
            },
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
    ]
