# Generated by Django 4.2.3 on 2023-07-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0008_anuncioanimal_delete_animal_delete_anuncio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncioanimal',
            old_name='id_cor_do_pelo_FK',
            new_name='id_cor_do_pelo_fk',
        ),
        migrations.RenameField(
            model_name='anuncioanimal',
            old_name='id_porte_tamanho_FK',
            new_name='id_porte_tamanho_fk',
        ),
        migrations.RenameField(
            model_name='associacoesdeanimais',
            old_name='id_zona_do_pais_FK',
            new_name='id_zona_do_pais_fk',
        ),
    ]
