# Generated by Django 4.2.3 on 2023-07-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0009_rename_id_cor_do_pelo_fk_anuncioanimal_id_cor_do_pelo_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioanimal',
            name='id_zona_do_pais_fk',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='animais_para_adocao.zonasdopais'),
            preserve_default=False,
        ),
    ]
