# Generated by Django 4.2.3 on 2023-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0011_medidasparaajudar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidasparaajudar',
            old_name='medida',
            new_name='medida_texto',
        ),
        migrations.AddField(
            model_name='medidasparaajudar',
            name='medida_titulo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
