# Generated by Django 4.2.3 on 2023-07-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais_para_adocao', '0012_rename_medida_medidasparaajudar_medida_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioanimal',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
