# Generated by Django 4.2.3 on 2023-07-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0013_anuncioanimal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioanimal',
            name='anuncio_estado',
            field=models.BooleanField(default=True),
        ),
    ]
