# Generated by Django 4.2.3 on 2023-07-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais_para_adocao', '0014_anuncioanimal_anuncio_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CondicoesParaAnunciar',
        ),
    ]
